parameters:
  env(AUXMONEY_OPENTRACING_AGENT_PORT): '9411'
  env(AUXMONEY_OPENTRACING_SAMPLER_CLASS): Zipkin\Samplers\BinarySampler
  env(AUXMONEY_OPENTRACING_SAMPLER_VALUE): 'true'

services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Auxmoney\OpentracingBundle\Factory\TracerFactory:
    class: Auxmoney\OpentracingBundle\Factory\ZipkinTracerFactory

  Auxmoney\OpentracingBundle\Factory\SamplerFactory:
    class: Auxmoney\OpentracingBundle\Factory\ZipkinSamplerFactory
